### ISSUE TITLE
Rabbitmq - no queue details

### ISSUE THREAD

**Issue by glmrenard** [pivotalsoftware/newrelic_pivotal_agent#22]
Hello,

I use the pivotal agent to monitor a rabbitmq server with several queue but on newrelic I have no per queue info, just an overview one.
Did I miss something ?

Best regards,

**Comment by cssonddos** [comment]
Hello @wesschlichter, i installed this version, but i`m still not seeing data in the Queues dashboard.
I have a 6 nodes cluster, more than 1k queues and 10 virtual hosts (including /). Can this environment size impact the plugin?

Regards
