### ISSUE TITLE
Cannot configure alerts

### ISSUE THREAD

**Issue by jhulst** [pivotalsoftware/newrelic_pivotal_agent#38]
When trying to configure a host, I don't see any options in the gear dropdown. Tried from multiple browsers and saw same behavior.

![screen shot 2014-08-18 at 3 01 38 pm](https://cloud.githubusercontent.com/assets/347239/3956340/24f38e4c-270a-11e4-9aa3-4f54ee075200.png)

**Comment by jayashreen** [comment]
Not sure if you still see this issue, but i have been able to get the drop down to set alert conditions. 
Sometimes, the data doesnt load for me, opening up in a incognito window always helps.

**Comment by wesschlichter** [comment]
@jhulst This is probably an issue with the new relic UI or as indicted by @jayashreen . Since this issue hasn't been updated since in a while I'm going to close it.
