### ISSUE TITLE
unable to run redis

### ISSUE THREAD

**Issue by azfarhashmi** [pivotalsoftware/newrelic_pivotal_agent#61]
I am getting below error when trying to load only redis plugin.  
./pivotal_agent:41: undefined method `require_relative' for main:Object (NoMethodError)

redis (3.2.1)
newrelic_plugin (1.3.1)
ruby (1.8)

All other plugins are disabled (hashed) in config/newrelic_plugin.yml

**Comment by carlhoerberg** [comment]
You need a newer Ruby version. Ruby 1.8 is deprecated since many years ago.

**Comment by azfarhashmi** [comment]
I dont know why debian is so slow to provide newer versions.
