### ISSUE TITLE
Transfer maintenance ownership of this module

### ISSUE THREAD

**Issue by johanbjork** [pivotalsoftware/newrelic_pivotal_agent#73]
Hi Pivotal,

How about you resume maintenance of this module? Many nice PRs waiting for approval. Alternatively perhaps transfer ownership or add a team contributor who's interested in developing it further.

For exampel this guy @carlhoerberg seems to be very capable with many good rabbit contribs.

**Comment by rqbanerjee** [comment]
This fork is obviously dead. Are there any up-to-date forks? Doesn't look like carl mentioned above has a fork.

**Comment by carlhoerberg** [comment]
We maintain a fork here https://github.com/cloudamqp/newrelic_pivotal_agent
